<?php

return [
    'english'=>[
                    [
                        "title" => "Information Technology",
                        "fields" => [
                            "Software Developer",
                            "Web Developer",
                            "Mobile App Developer",
                            "Database Administrator",
                            "Systems Analyst",
                            "Network Engineer",
                            "Cybersecurity Analyst",
                            "IT Project Manager",
                        ],
                    ],
                    [
                        "title" => "Healthcare",
                        "fields" => [
                            "Doctor",
                            "Nurse",
                            "Pharmacist",
                            "Physical Therapist",
                            "Occupational Therapist",
                            "Medical Assistant",
                            "Radiologist",
                            "Psychiatrist",
                        ],
                    ],
                    [
                        "title" => "Education",
                        "fields" => [
                            "Teacher",
                            "Professor",
                            "School Counselor",
                            "Librarian",
                            "Education Consultant",
                            "Special Education Teacher",
                            "Curriculum Developer",
                        ],
                    ],
                    [
                        "title" => "Business and Finance",
                        "fields" => [
                            "Accountant",
                            "Financial Analyst",
                            "Investment Banker",
                            "Marketing Manager",
                            "Human Resources Manager",
                            "Operations Manager",
                            "Business Consultant",
                            "Entrepreneur",
                        ],
                    ],
                    [
                        "title" => "Engineering",
                        "fields" => [
                            "Civil Engineer",
                            "Mechanical Engineer",
                            "Electrical Engineer",
                            "Chemical Engineer",
                            "Aerospace Engineer",
                            "Environmental Engineer",
                            "Biomedical Engineer",
                            "Computer Hardware Engineer",
                        ],
                    ],
                    [
                        "title" => "Creative Arts",
                        "fields" => [
                            "Graphic Designer",
                            "Illustrator",
                            "Animator",
                            "Photographer",
                            "Film Director",
                            "Musician",
                            "Writer",
                            "Actor/Actress",
                        ],
                    ],
                    [
                        "title" => "Legal",
                        "fields" => [
                            "Lawyer",
                            "Paralegal",
                            "Legal Secretary",
                            "Judge",
                            "Legal Consultant",
                            "Court Reporter",
                            "Corporate Counsel",
                            "Intellectual Property Attorney",
                        ],
                    ],
                    [
                        "title" => "Science",
                        "fields" => [
                            "Biologist",
                            "Chemist",
                            "Physicist",
                            "Geologist",
                            "Astronomer",
                            "Environmental Scientist",
                            "Research Scientist",
                            "Data Scientist",
                        ],
                    ],
                    [
                        "title" => "Healthcare and Wellness",
                        "fields" => [
                            "Nutritionist",
                            "Personal Trainer",
                            "Wellness Coach",
                            "Massage Therapist",
                            "Yoga Instructor",
                            "Acupuncturist",
                            "Holistic Health Practitioner",
                            "Mental Health Counselor",
                        ],
                    ],
                    [
                        "title" => "Trades and Services",
                        "fields" => [
                            "Electrician",
                            "Plumber",
                            "Carpenter",
                            "HVAC Technician",
                            "Mechanic",
                            "Landscaper",
                            "Chef",
                            "Hair Stylist/Barber",
                        ],
                    ],
                    [
                        "title" => "Media and Communication",
                        "fields" => [
                            "Journalist",
                            "Public Relations Specialist",
                            "Social Media Manager",
                            "Content Creator",
                            "Copywriter",
                            "Broadcast News Analyst",
                            "Editor",
                            "Communications Director",
                        ],
                    ],
                    [
                        "title" => "Miscellaneous",
                        "fields" => [
                            "Real Estate Agent",
                            "Event Planner",
                            "Travel Agent",
                            "Interpreter/Translator",
                            "Archaeologist",
                            "Detective/Investigator",
                            "Pilot",
                            "Firefighter",
                        ],
                    ]
    ],
    'turkish'=>[
            [
                "title" => "Bilgi Teknolojisi",
                "fields" => [
                    "Yazılım Geliştirici",
                    "Web Geliştirici",
                    "Mobil Uygulama Geliştirici",
                    "Veritabanı Yöneticisi",
                    "Sistem Analisti",
                    "Ağ Mühendisi",
                    "Siber Güvenlik Analisti",
                    "BT Proje Yöneticisi",
                ],
            ],
            [
                "title" => "Sağlık",
                "fields" => [
                    "Doktor",
                    "Hemşire",
                    "Eczacı",
                    "Fizyoterapist",
                    "Ergoterapist",
                    "Tıbbi Asistan",
                    "Radyolog",
                    "Psikiyatrist",
                ],
            ],
            [
                "title" => "Eğitim",
                "fields" => [
                    "Öğretmen",
                    "Profesör",
                    "Okul Danışmanı",
                    "Kütüphaneci",
                    "Eğitim Danışmanı",
                    "Özel Eğitim Öğretmeni",
                    "Müfredat Geliştirici",
                ],
            ],
            [
                "title" => "İşletme ve Finans",
                "fields" => [
                    "Muhasebeci",
                    "Finansal Analist",
                    "Yatırım Bankacısı",
                    "Pazarlama Müdürü",
                    "İnsan Kaynakları Müdürü",
                    "Operasyonlar Müdürü",
                    "İş Danışmanı",
                    "Girişimci",
                ],
            ],
            [
                "title" => "Mühendislik",
                "fields" => [
                    "İnşaat Mühendisi",
                    "Makine Mühendisi",
                    "Elektrik Mühendisi",
                    "Kimya Mühendisi",
                    "Havacılık Mühendisi",
                    "Çevre Mühendisi",
                    "Biyomedikal Mühendisi",
                    "Bilgisayar Donanım Mühendisi",
                ],
            ],
            [
                "title" => "Yaratıcı Sanatlar",
                "fields" => [
                    "Grafik Tasarımcı",
                    "İllüstratör",
                    "Animatör",
                    "Fotoğrafçı",
                    "Film Yönetmeni",
                    "Müzisyen",
                    "Yazar",
                    "Oyuncu",
                ],
            ],
            [
                "title" => "Hukuk",
                "fields" => [
                    "Avukat",
                    "Hukuk Müşaviri",
                    "Hukuk Sekreteri",
                    "Hakim",
                    "Hukuk Danışmanı",
                    "Mahkeme Muhabiri",
                    "Kurumsal Avukat",
                    "Fikri Mülkiyet Avukatı",
                ],
            ],
            [
                "title" => "Bilim",
                "fields" => [
                    "Biyolog",
                    "Kimyager",
                    "Fizikçi",
                    "Jeolog",
                    "Astronom",
                    "Çevre Bilimci",
                    "Araştırma Bilimcisi",
                    "Veri Bilimci",
                ],
            ],
            [
                "title" => "Sağlık ve İyi Olma",
                "fields" => [
                    "Beslenme Uzmanı",
                    "Kişisel Antrenör",
                    "İyi Olma Koçu",
                    "Masaj Terapisti",
                    "Yoga Eğitmeni",
                    "Akupunkturist",
                    "Holistik Sağlık Uygulayıcısı",
                    "Ruh Sağlığı Danışmanı",
                ],
            ],
            [
                "title" => "Meslekler ve Hizmetler",
                "fields" => [
                    "Elektrikçi",
                    "Tesisatçı",
                    "Marangoz",
                    "HVAC Teknisyeni",
                    "Tamirci",
                    "Peyzaj Mimarı",
                    "Şef",
                    "Kuaför",
                ],
            ],
            [
                "title" => "Medya ve İletişim",
                "fields" => [
                    "Gazeteci",
                    "Halkla İlişkiler Uzmanı",
                    "Sosyal Medya Yöneticisi",
                    "İçerik Oluşturucu",
                    "Kopya Yazarı",
                    "Radyo ve Televizyon Haber Analisti",
                    "Editör",
                    "İletişim Direktörü",
                ],
            ],
            [
                "title" => "Çeşitli",
                "fields" => [
                    "Emlakçı",
                    "Etkinlik Planlayıcısı",
                    "Seyahat Acentesi",
                    "Tercüman",
                    "Arkeolog",
                    "Dedektif",
                    "Pilot",
                    "İtfaiyeci",
                ],
            ]
    ],

];
